const houseActionTypes = {
  TRENDING_FETCH_START: "TRENDING_FETCH_START",
  TRENDING_FETCH_SUCCESS: "TRENDING_FETCH_SUCCESS",
  TRENDING_FETCH_FAILURE: "TRENDING_FETCH_FAILURE",

  CATEGORY_FETCH_START: "CATEGORY_FETCH_START",
  CATEGORY_FETCH_SUCCESS: "CATEGORY_FETCH_SUCCESS",
  CATEGORY_FETCH_FAILURE: "CATEGORY_FETCH_FAILURE",

  HOUSES_FETCH_START: "HOUSES_FETCH_START",
  HOUSES_FETCH_SUCCESS: "HOUSES_FETCH_SUCCESS",
  HOUSES_FETCH_FAILURE: "HOUSES_FETCH_FAILURE",
};

export default houseActionTypes;
