const actionTypes = {
  // USER LOGIN ACTION TYPES
  EMAIL_LOGIN_START: "EMAIL_LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  //USER REGISTER ACTION TYPES
  EMAIL_REGISTER_START: "EMAIL_REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  //USER SIGNOUT ACTIONS
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  //set current user
  SET_USER_TOKEN: "SET_USER_TOKEN",
  SET_CURRENT_USER: "SET_CURRENT_USER",

  //Clear login or signup errors
  CLEAR_USER_ERROR: "CLEAR_USER_ERROR",

  //USER posts fetch ACTIONS
  POST_FETCH_START: "POST_FETCH_START",
  POST_FETCH_SUCCESS: "POST_FETCH_SUCCESS",
  POST_FETCH_FAILURE: "POST_FETCH_FAILURE",

  //USER posts delet ACTIONS
  POST_DELETE_START: "POST_DELETE_START",
  POST_DELETE_SUCCESS: "POST_DELETE_SUCCESS",
  POST_DELETE_FAILURE: "POST_DELETE_FAILURE",

  //USER posts publish ACTIONS
  POST_PUBLISH_START: "POST_PUBLISH_START",
  POST_PUBLISH_SUCCESS: "POST_PUBLISH_SUCCESS",
  POST_PUBLISH_FAILURE: "POST_PUBLISH_FAILURE",

  //USER fetch ACTIONS
  USER_FETCH_START: "USER_FETCH_START",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
};

export default actionTypes;
